import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      {/* navbar */}
      <Nav />
      {/* results */}
      <Results />
      
    </div>
  )
}

export async function getServerSideProps(Contex){
  const genre = contex.query.genre;
}
